name         = "App-sdif"
script_files = [ "script/sdif", "script/cdif", "script/watchdiff" ]
badges       = [ 'github-actions/test', 'metacpan' ]
authority    = "cpan:UTASHIRO"
module_maker = "ModuleBuildTiny"

[release]
branch = "master"

[unsupported]
os = [
    "MSWin32",
]
