name: test

on:
  push:
    paths-ignore:
      - '**.md'
      - 'docs/**'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        perl: [ '5.40', '5.30', '5.24', '5.18', '5.14' ]
    name: Perl ${{ matrix.perl }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
      - run: perl -V
      - uses: tecolicom/actions-use-apt-tools@v1
        with:
          tools: mecab mecab-ipadic-utf8
          method: timestamp
      - run: |
          mecab --version
          echo 私の名前は中野です | mecab
      - run: cpanm --installdeps --notest --quiet .
      - run: prove -lv t
